apiVersion: apps/v1
kind: Deployment
metadata:
  name: khaledmohamedatia
  labels:
    app: khaledmohamedatia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: khaledmohamedatia
  template:
    metadata:
      labels:
        app: khaledmohamedatia
    spec:
      containers:
      - name: khaledmohamedatia
        image: khaledmohamedatia/app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  clusterIP: 10.96.0.1 
  type: LoadBalancer